name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:
    branches: ["main", "master"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: akiradreams
          template: classic
          config_timezone: Europe/Madrid

          # General Overview
          filename: github-metrics-general.svg
          base: header, activity, community, repositories

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-languages.svg
          plugin_languages: yes
          plugin_languages_sections: most-used
          config_timezone: Europe/Madrid

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-music.svg
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: genesisdy
          plugin_music_mode: top
          plugin_music_limit: 9
          config_timezone: Europe/Madrid

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-rss.svg
          plugin_rss: yes
          plugin_rss_source: https://feeds.feedburner.com/TheHackersNews
          plugin_rss_limit: 4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-stock.svg
          plugin_stock: yes
          plugin_stock_symbol: ETH
          plugin_stock_duration: 1d
          plugin_stock_interval: 1m

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_user: current
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, languages, editors, os
