name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics-left:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: left.svg
          user: akiradreams
          template: classic
          base: header, repositories, activity
          config_display: large
          config_padding: 0, 5% # simula más margen
          plugin_languages: yes
          plugin_rss: yes
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: genesisdy
          plugin_music_mode: top
          plugin_music_limit: 9

  github-metrics-right:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: right.svg
          user: akiradreams
          template: classic
          base: ""
          config_display: large
          config_padding: 0, 5% # igual que arriba
          plugin_wakatime: yes
          plugin_wakatime_user: current
          plugin_wakatime_sections: time, projects, languages
          plugin_stock: yes
          plugin_stock_symbol: ETH
          plugin_stock_duration: 1d
          plugin_stock_interval: 1m