name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:

  github-metrics-header:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-header.svg
          user: akiradreams
          template: classic
          base: header

  github-metrics-repositories:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-repositories.svg
          user: akiradreams
          template: classic
          base: repositories

  github-metrics-activity:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-activity.svg
          user: akiradreams
          template: classic
          base: activity

  github-metrics-languages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-languages.svg
          user: akiradreams
          plugin_languages: yes

  github-metrics-rss:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-rss.svg
          user: akiradreams
          plugin_rss: yes
          plugin_rss_source: https://feeds.feedburner.com/TheHackersNews
          plugin_rss_limit: 4

  github-metrics-music:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-music.svg
          user: akiradreams
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_user: genesisdy
          plugin_music_mode: top
          plugin_music_limit: 9

  github-metrics-wakatime:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-wakatime.svg
          user: akiradreams
          plugin_wakatime: yes
          plugin_wakatime_user: current
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_sections: time, projects, languages

  github-metrics-stock-arb:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-stock-arb.svg
          user: akiradreams
          plugin_stock: yes
          plugin_stock_symbol: ARB-EUR
          plugin_stock_duration: 1d
          plugin_stock_interval: 1m

  github-metrics-stock-sui:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metric-stock-sui.svg
          user: akiradreams
          plugin_stock: yes
          plugin_stock_symbol: SUI1-EUR
          plugin_stock_duration: 1d
          plugin_stock_interval: 1m
